# Generated by Django 5.2 on 2025-06-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="data_joined",
            new_name="date_joined",
        ),
    ]
