# Generated by Django 5.2.3 on 2025-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="orderded",
            new_name="ordered",
        ),
        migrations.AlterField(
            model_name="order",
            name="is_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
