# Generated by Django 5.2.3 on 2025-08-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_orderded_orderproduct_ordered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
