# Generated by Django 5.2.3 on 2025-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderproduct_size"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
